---
- name: Pull docker image
  hosts: all
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker front-end image
      shell: docker pull sagarshirke2674/spe:cc1

    - name: pull docker server image
      shell: docker pull sagarshirke2674/spe:ss1

    - name: Create back-end container

      docker_container:
        name: backend

        image: sagarshirke2674/spe:ss1

        ports:
          - "5000:5000"

    - name: Create front-end container

      docker_container:
        name: frontend

        image: sagarshirke2674/spe:cc1

        interactive: true

        ports:
          - "3000:3000"
