
---
- name: Pull docker image
  hosts: all
  tasks:
    - name: copy docker compose file
      copy: 
        src: ./docker-compose.yml
        dest: ./

    - name: Start docker service
      service:
        name: docker
        state: started

    # - name: pull docker front-end image
    #   shell: docker pull sagarshirke2674/spe:cc1

    # - name: pull docker server image
    #   shell: docker pull sagarshirke2674/spe:ss1

    - name: docker compose pull
      command: docker-compose pull


    - name: stop previous back-end container
      shell: docker rm -f sagarshirke2674/spe:ss1

    - name: stop previous front-end container
      shell: docker rm -f sagarshirke2674/spe:cc1


    - name: running docker compose file
      shell: docker-compose up 
