version: "3"
services:
  react-app:
    image: sagarshirke2674/spe:cc1
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
  api-server:
    image: sagarshirke2674/spe:ss1
    ports:
      - "5000:5000"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
